[package]
name = "dusk-plonk"
version = "0.8.2"
authors = ["Kevaundray Wedderburn <kevtheappdev@gmail.com>",
           "Luke Pearson <luke@dusk.network>", 
           "CPerezz <carlos@dusk.network>"] 
readme = "README.md"
repository = "https://github.com/dusk-network/plonk"
keywords = ["cryptography", "plonk", "zk-snarks", "zero-knowledge", "crypto"]
categories =["algorithms", "cryptography", "science"]
description = "A pure-Rust implementation of the PLONK ZK-Proof algorithm"
exclude = [
    "**/.gitignore",
    ".gitignore",
    "Cargo.lock",
    "**/examples",
    "benchmarks/",
    ".github/"
]
license = "MPL-2.0"
edition = "2018"

[dependencies]
ark-ec = "0.3"
merlin = {version = "3.0", default-features = false}
rand_core = {version="0.6", default-features=false}
itertools = {version = "0.9", default-features = false}
hashbrown = {version = "0.9", default-features=false, features = ["ahash"]}
rayon = {version = "1.3", optional = true}
cfg-if = "1.0"

[dev-dependencies]
tempdir = "0.3"

[features]
default = ["std"]
std = [
    "rand_core/std",
    "itertools/default",
    "hashbrown/default",
    "rayon"
]
trace = []
trace-print = ["trace"]
